import json
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
import os

# Define the cells for the notebook
cells = []

# Cell 1: Markdown Title
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# End-to-End Sales Forecasting & Demand Intelligence System\n",
        "This notebook contains the complete implementation of the Sales Forecasting & Demand Intelligence System, structured as follows:\n",
        "- **Task 1**: Data Loading, Merging & Deep Exploration\n",
        "- **Task 2**: Time Series Analysis & Decomposition (Trend, Seasonality, Residual, Stationarity)\n",
        "- **Task 3**: Sales Forecasting using 3 Different Models (SARIMA, Prophet, XGBoost) and evaluation\n",
        "- **Task 4**: Product Category & Region Level Forecasting\n",
        "- **Task 5**: Anomaly Detection in Sales Data (Isolation Forest vs Z-Score)\n",
        "- **Task 6**: Product Demand Segmentation using K-Means Clustering"
    ]
})

# Cell 2: Imports & Styling
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import os\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from statsmodels.tsa.seasonal import seasonal_decompose\n",
        "from statsmodels.tsa.stattools import adfuller\n",
        "from statsmodels.tsa.statespace.sarimax import SARIMAX\n",
        "from prophet import Prophet\n",
        "from xgboost import XGBRegressor\n",
        "from sklearn.ensemble import IsolationForest\n",
        "from sklearn.cluster import KMeans\n",
        "from sklearn.decomposition import PCA\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "import warnings\n",
        "\n",
        "warnings.filterwarnings('ignore')\n",
        "sns.set_theme(style='darkgrid')\n",
        "plt.rcParams['figure.figsize'] = (12, 6)\n",
        "os.makedirs('Charts', exist_ok=True)\n",
        "print('Imports successful!')"
    ]
})

# Cell 3: Markdown for Task 1
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Task 1 — Data Loading, Merging & Deep Exploration\n",
        "In this section, we load the dataset, parse dates, extract features, check for data issues, and aggregate sales into daily, weekly, and monthly intervals. We also answer four core exploratory questions."
    ]
})

# Cell 4: Task 1 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Load dataset\n",
        "df = pd.read_csv('train.csv')\n",
        "\n",
        "# Parse Order Date and Ship Date as datetime\n",
        "df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)\n",
        "df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)\n",
        "\n",
        "# Extract time features\n",
        "df['Year'] = df['Order Date'].dt.year\n",
        "df['Month'] = df['Order Date'].dt.month\n",
        "df['Week Number'] = df['Order Date'].dt.isocalendar().week\n",
        "df['Day of Week'] = df['Order Date'].dt.day_name()\n",
        "df['Quarter'] = df['Order Date'].dt.quarter\n",
        "\n",
        "def get_season(month):\n",
        "    if month in [12, 1, 2]:\n",
        "        return 'Winter'\n",
        "    elif month in [3, 4, 5]:\n",
        "        return 'Spring'\n",
        "    elif month in [6, 7, 8]:\n",
        "        return 'Summer'\n",
        "    else:\n",
        "        return 'Autumn'\n",
        "\n",
        "df['Season'] = df['Month'].apply(get_season)\n",
        "\n",
        "# Check for missing values, duplicates, and data types\n",
        "print('=== Data Checks ===')\n",
        "print('Missing Values:\\n', df.isnull().sum())\n",
        "print('\\nDuplicate Count:', df.duplicated().sum())\n",
        "print('\\nData Types:\\n', df.dtypes)\n",
        "\n",
        "# Aggregate daily, weekly, and monthly totals\n",
        "daily_sales = df.groupby('Order Date')['Sales'].sum().reset_index()\n",
        "weekly_sales = df.resample('W', on='Order Date')['Sales'].sum().reset_index()\n",
        "monthly_sales = df.resample('MS', on='Order Date')['Sales'].sum().reset_index()\n",
        "\n",
        "print('\\nMonthly Aggregation Sample:\\n', monthly_sales.head())"
    ]
})

# Cell 5: Markdown for Task 1 EDA Answers
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### EDA Question Answers\n",
        "\n",
        "#### **Q1: Which product category generates the highest total revenue?**\n",
        "Let's calculate the total revenue generated by category."
    ]
})

# Cell 6: Q1 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "category_revenue = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)\n",
        "print('Total Revenue by Category:')\n",
        "for cat, rev in category_revenue.items():\n",
        "    print(f'- {cat}: ${rev:,.2f}')"
    ]
})

# Cell 7: Markdown Q2
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "#### **Q2: Which region has the most consistent sales growth over 4 years?**\n",
        "We calculate YoY sales for each region and evaluate growth volatility (consistency) using the standard deviation of growth rates."
    ]
})

# Cell 8: Q2 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "region_yearly = df.groupby(['Region', 'Year'])['Sales'].sum().unstack(level=0)\n",
        "region_growth = region_yearly.pct_change().dropna()\n",
        "print('Year-over-Year growth rates by Region:')\n",
        "print(region_growth)\n",
        "print('\\nVolatility of growth rates (lower = more consistent):')\n",
        "print(region_growth.std())"
    ]
})

# Cell 9: Markdown Q3
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "#### **Q3: What is the average time between Order Date and Ship Date — and does it vary by region?**\n",
        "We compute the shipping duration in days and check the mean across regions."
    ]
})

# Cell 10: Q3 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "df['Ship Time'] = (df['Ship Date'] - df['Order Date']).dt.days\n",
        "print(f'Overall average shipping time: {df[\"Ship Time\"].mean():.2f} days\\n')\n",
        "print('Average shipping time by Region:')\n",
        "print(df.groupby('Region')['Ship Time'].mean())"
    ]
})

# Cell 11: Markdown Q4
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "#### **Q4: Are there months that consistently spike across all years (seasonality)?**\n",
        "We examine the average sales pattern across different months of the year."
    ]
})

# Cell 12: Q4 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "monthly_patterns = df.groupby(['Year', 'Month'])['Sales'].sum().unstack(level=0)\n",
        "plt.figure(figsize=(10, 5))\n",
        "sns.lineplot(data=monthly_patterns, marker='o', linewidth=2)\n",
        "plt.title('Monthly Sales Seasonality by Year', fontweight='bold')\n",
        "plt.xlabel('Month')\n",
        "plt.ylabel('Total Sales ($)')\n",
        "plt.xticks(range(1, 13))\n",
        "plt.tight_layout()\n",
        "plt.savefig('Charts/eda_seasonality_patterns.png', dpi=300)\n",
        "plt.show()\n",
        "\n",
        "print('Average Sales by Month:')\n",
        "print(monthly_patterns.mean(axis=1).sort_values(ascending=False))"
    ]
})

# Cell 13: Markdown Task 2
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Task 2 — Time Series Analysis & Decomposition\n",
        "We examine the overall monthly sales trend, decompose the signal, and check for stationarity using the Augmented Dickey-Fuller (ADF) test."
    ]
})

# Cell 14: Task 2 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "ts_monthly = monthly_sales.set_index('Order Date')['Sales']\n",
        "\n",
        "# Plot trend\n",
        "plt.figure(figsize=(12, 5))\n",
        "plt.plot(ts_monthly.index, ts_monthly.values, marker='o', color='#1f77b4', linewidth=2)\n",
        "plt.title('Overall Monthly Sales Trend (2015-2018)', fontsize=14, fontweight='bold')\n",
        "plt.xlabel('Date')\n",
        "plt.ylabel('Sales ($)')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Apply decomposition\n",
        "decomposition = seasonal_decompose(ts_monthly, model='additive', period=12)\n",
        "fig, axes = plt.subplots(4, 1, figsize=(12, 10), sharex=True)\n",
        "decomposition.observed.plot(ax=axes[0], color='#1f77b4', legend=False)\n",
        "axes[0].set_ylabel('Observed')\n",
        "axes[0].set_title('Time Series Decomposition', fontsize=14, fontweight='bold')\n",
        "decomposition.trend.plot(ax=axes[1], color='#ff7f0e', legend=False)\n",
        "axes[1].set_ylabel('Trend')\n",
        "decomposition.seasonal.plot(ax=axes[2], color='#2ca02c', legend=False)\n",
        "axes[2].set_ylabel('Seasonal')\n",
        "decomposition.resid.plot(ax=axes[3], color='#d62728', style='o', legend=False)\n",
        "axes[3].set_ylabel('Residual')\n",
        "axes[3].axhline(0, color='black', linestyle='--')\n",
        "plt.xlabel('Date')\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# Cell 15: Markdown Task 2 Observations & ADF
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### Observations from Decomposition:\n",
        "1. **Trend**: The sales trend shows an upward trajectory over the 4 years, reflecting business expansion and sales growth.\n",
        "2. **Seasonality**: There is a strong, repeating annual seasonal pattern with major peaks in November and December, and a deep drop in January/February.\n",
        "3. **Residual/Noise**: The noise is highest around November/December which indicates that holiday surges have large fluctuations year-over-year.\n",
        "\n",
        "### Stationarity Check (Augmented Dickey-Fuller Test)\n",
        "Stationarity means that the statistical properties of a process generating a time series do not change over time (i.e., constant mean, constant variance, and autocovariance independent of time). Stationary series are much easier to model because their statistical characteristics are stable.\n",
        "Let's check the ADF test results."
    ]
})

# Cell 16: ADF Test Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "adf_result = adfuller(ts_monthly)\n",
        "print(f'ADF Statistic: {adf_result[0]:.4f}')\n",
        "print(f'p-value: {adf_result[1]:.4f}')\n",
        "print('Critical Values:')\n",
        "for key, value in adf_result[4].items():\n",
        "    print(f'\\t{key}: {value:.4f}')\n",
        "\n",
        "is_stationary = adf_result[1] < 0.05\n",
        "print(f'\\nIs the time series stationary? {is_stationary}')"
    ]
})

# Cell 17: Markdown Task 3
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Task 3 — Sales Forecasting using 3 Different Models\n",
        "We build and compare 3 different models: SARIMA, Prophet, and XGBoost.\n",
        "- The data is split: Train on first 45 months (Jan 2015 - Sep 2018), and Test on last 3 months (Oct 2018 - Dec 2018) to calculate MAE, RMSE, and MAPE.\n",
        "- The best model is chosen based on performance metrics, and a 3-month future forecast (Jan - Mar 2019) is generated."
    ]
})

# Cell 18: Model 1 Code (SARIMA)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "train_size = len(ts_monthly) - 3\n",
        "train_ts = ts_monthly.iloc[:train_size]\n",
        "test_ts = ts_monthly.iloc[train_size:]\n",
        "\n",
        "# Grid search for best SARIMA parameters\n",
        "best_aic = float('inf')\n",
        "best_order = (0, 1, 1)\n",
        "best_seasonal = (0, 1, 1, 12)\n",
        "\n",
        "for p in [0, 1, 2]:\n",
        "    for d in [0, 1]:\n",
        "        for q in [0, 1]:\n",
        "            for P in [0, 1]:\n",
        "                for D in [0, 1]:\n",
        "                    for Q in [0, 1]:\n",
        "                        try:\n",
        "                            model = SARIMAX(train_ts, order=(p,d,q), seasonal_order=(P,D,Q,12),\n",
        "                                            enforce_stationarity=False, enforce_invertibility=False)\n",
        "                            res = model.fit(disp=False)\n",
        "                            if res.aic < best_aic:\n",
        "                                best_aic = res.aic\n",
        "                                best_order = (p, d, q)\n",
        "                                best_seasonal = (P, D, Q, 12)\n",
        "                        except:\n",
        "                            continue\n",
        "\n",
        "print(f'Best SARIMA Parameters: Order={best_order}, Seasonal={best_seasonal} (AIC={best_aic:.2f})')\n",
        "\n",
        "# Fit on Train and predict Test\n",
        "sarima_model = SARIMAX(train_ts, order=best_order, seasonal_order=best_seasonal,\n",
        "                       enforce_stationarity=False, enforce_invertibility=False)\n",
        "sarima_res = sarima_model.fit(disp=False)\n",
        "sarima_pred = sarima_res.forecast(steps=3)\n",
        "\n",
        "# Future forecast using all data\n",
        "sarima_full = SARIMAX(ts_monthly, order=best_order, seasonal_order=best_seasonal,\n",
        "                      enforce_stationarity=False, enforce_invertibility=False)\n",
        "sarima_full_res = sarima_full.fit(disp=False)\n",
        "sarima_future = sarima_full_res.get_forecast(steps=3)\n",
        "sarima_future_mean = sarima_future.predicted_mean\n",
        "sarima_conf = sarima_future.conf_int()\n",
        "\n",
        "print('SARIMA Test Preds:', sarima_pred.values)\n",
        "print('SARIMA Future Preds:', sarima_future_mean.values)"
    ]
})

# Cell 19: Model 2 Code (Prophet)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Format for Prophet\n",
        "df_p_train = train_ts.reset_index().rename(columns={'Order Date': 'ds', 'Sales': 'y'})\n",
        "prophet_model = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)\n",
        "prophet_model.fit(df_p_train)\n",
        "future_test = prophet_model.make_future_dataframe(periods=3, freq='MS')\n",
        "prophet_forecast = prophet_model.predict(future_test)\n",
        "prophet_pred = prophet_forecast.iloc[-3:]['yhat'].values\n",
        "\n",
        "# Fit on full data\n",
        "df_p_full = ts_monthly.reset_index().rename(columns={'Order Date': 'ds', 'Sales': 'y'})\n",
        "prophet_full_model = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)\n",
        "prophet_full_model.fit(df_p_full)\n",
        "future_dates_df = prophet_full_model.make_future_dataframe(periods=3, freq='MS')\n",
        "prophet_future_forecast = prophet_full_model.predict(future_dates_df)\n",
        "prophet_future = prophet_future_forecast.iloc[-3:]['yhat'].values\n",
        "prophet_future_lower = prophet_future_forecast.iloc[-3:]['yhat_lower'].values\n",
        "prophet_future_upper = prophet_future_forecast.iloc[-3:]['yhat_upper'].values\n",
        "\n",
        "# Plot Prophet Seasonality breakdowns\n",
        "prophet_full_model.plot_components(prophet_future_forecast)\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# Cell 20: Model 3 Code (XGBoost)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "def create_xgboost_features(series):\n",
        "    df_features = pd.DataFrame(series)\n",
        "    df_features.columns = ['y']\n",
        "    df_features['Lag_1'] = df_features['y'].shift(1)\n",
        "    df_features['Lag_2'] = df_features['y'].shift(2)\n",
        "    df_features['Lag_3'] = df_features['y'].shift(3)\n",
        "    df_features['Rolling_Mean_3'] = df_features['y'].shift(1).rolling(window=3).mean()\n",
        "    df_features['Month'] = df_features.index.month\n",
        "    df_features['Quarter'] = df_features.index.quarter\n",
        "    df_features['Season_Num'] = df_features['Month'].apply(lambda x: 1 if x in [12, 1, 2] else (2 if x in [3, 4, 5] else (3 if x in [6, 7, 8] else 4)))\n",
        "    return df_features.dropna()\n",
        "\n",
        "xgb_data = create_xgboost_features(ts_monthly)\n",
        "xgb_train = xgb_data.iloc[:train_size - 3]\n",
        "\n",
        "X_train = xgb_train.drop(columns=['y'])\n",
        "y_train = xgb_train['y']\n",
        "\n",
        "xgb_reg = XGBRegressor(n_estimators=100, max_depth=4, learning_rate=0.05, random_state=42)\n",
        "xgb_reg.fit(X_train, y_train)\n",
        "\n",
        "# Recursive forecast on Test\n",
        "xgb_preds = []\n",
        "last_obs = list(train_ts.iloc[-3:])\n",
        "for i in range(3):\n",
        "    lag1, lag2, lag3 = last_obs[-1], last_obs[-2], last_obs[-3]\n",
        "    roll3 = np.mean(last_obs[-3:])\n",
        "    month = test_ts.index[i].month\n",
        "    quarter = test_ts.index[i].quarter\n",
        "    season = 1 if month in [12,1,2] else (2 if month in [3,4,5] else (3 if month in [6,7,8] else 4))\n",
        "    x_input = pd.DataFrame([[lag1, lag2, lag3, roll3, month, quarter, season]],\n",
        "                           columns=['Lag_1', 'Lag_2', 'Lag_3', 'Rolling_Mean_3', 'Month', 'Quarter', 'Season_Num'])\n",
        "    pred_val = xgb_reg.predict(x_input)[0]\n",
        "    xgb_preds.append(pred_val)\n",
        "    last_obs.append(pred_val)\n",
        "\n",
        "xgb_pred = np.array(xgb_preds)\n",
        "\n",
        "# Fit on full data and predict future recursively\n",
        "xgb_reg_full = XGBRegressor(n_estimators=100, max_depth=4, learning_rate=0.05, random_state=42)\n",
        "X_full = xgb_data.drop(columns=['y'])\n",
        "y_full = xgb_data['y']\n",
        "xgb_reg_full.fit(X_full, y_full)\n",
        "\n",
        "xgb_futures = []\n",
        "last_obs_full = list(ts_monthly.iloc[-3:])\n",
        "future_dates = pd.date_range(start='2019-01-01', periods=3, freq='MS')\n",
        "for i in range(3):\n",
        "    lag1, lag2, lag3 = last_obs_full[-1], last_obs_full[-2], last_obs_full[-3]\n",
        "    roll3 = np.mean(last_obs_full[-3:])\n",
        "    month = future_dates[i].month\n",
        "    quarter = future_dates[i].quarter\n",
        "    season = 1 if month in [12,1,2] else (2 if month in [3,4,5] else (3 if month in [6,7,8] else 4))\n",
        "    x_input = pd.DataFrame([[lag1, lag2, lag3, roll3, month, quarter, season]],\n",
        "                           columns=['Lag_1', 'Lag_2', 'Lag_3', 'Rolling_Mean_3', 'Month', 'Quarter', 'Season_Num'])\n",
        "    pred_val = xgb_reg_full.predict(x_input)[0]\n",
        "    xgb_futures.append(pred_val)\n",
        "    last_obs_full.append(pred_val)\n",
        "\n",
        "xgb_future = np.array(xgb_futures)\n",
        "print('XGBoost Test Preds:', xgb_pred)\n",
        "print('XGBoost Future Preds:', xgb_future)"
    ]
})

# Cell 21: Model Comparison Table and Plots
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "def calculate_metrics(y_true, y_pred):\n",
        "    mae = np.mean(np.abs(y_true - y_pred))\n",
        "    rmse = np.sqrt(np.mean((y_true - y_pred)**2))\n",
        "    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100\n",
        "    return mae, rmse, mape\n",
        "\n",
        "m_sarima = calculate_metrics(test_ts.values, sarima_pred.values)\n",
        "m_prophet = calculate_metrics(test_ts.values, prophet_pred)\n",
        "m_xgb = calculate_metrics(test_ts.values, xgb_pred)\n",
        "\n",
        "comparison_df = pd.DataFrame({\n",
        "    'Model': ['SARIMA', 'Prophet', 'XGBoost'],\n",
        "    'MAE': [m_sarima[0], m_prophet[0], m_xgb[0]],\n",
        "    'RMSE': [m_sarima[1], m_prophet[1], m_xgb[1]],\n",
        "    'MAPE (%)': [m_sarima[2], m_prophet[2], m_xgb[2]],\n",
        "    'Forecast Month 1 (Jan 2019)': [sarima_future_mean.values[0], prophet_future[0], xgb_future[0]],\n",
        "    'Forecast Month 2 (Feb 2019)': [sarima_future_mean.values[1], prophet_future[1], xgb_future[1]],\n",
        "    'Forecast Month 3 (Mar 2019)': [sarima_future_mean.values[2], prophet_future[2], xgb_future[2]]\n",
        "})\n",
        "\n",
        "print('=== Model Evaluation Table ===')\n",
        "print(comparison_df.to_string(index=False))\n",
        "\n",
        "# Plot comparison on test set\n",
        "plt.figure(figsize=(12, 6))\n",
        "plt.plot(ts_monthly.index[-12:], ts_monthly.values[-12:], label='Actual Sales', color='black', linewidth=2, marker='o')\n",
        "plt.plot(test_ts.index, sarima_pred, label='SARIMA', color='blue', linestyle='--', marker='^')\n",
        "plt.plot(test_ts.index, prophet_pred, label='Prophet', color='orange', linestyle='--', marker='s')\n",
        "plt.plot(test_ts.index, xgb_pred, label='XGBoost', color='green', linestyle='--', marker='d')\n",
        "plt.title('Forecasting Model Performance on Test Set', fontsize=14, fontweight='bold')\n",
        "plt.xlabel('Date')\n",
        "plt.ylabel('Sales ($)')\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Plot future forecast of best model\n",
        "plt.figure(figsize=(12, 6))\n",
        "plt.plot(ts_monthly.index[-12:], ts_monthly.values[-12:], label='Historical Sales (2018)', color='black', linewidth=2, marker='o')\n",
        "plt.plot(future_dates, sarima_future_mean, label='SARIMA Future Forecast', color='blue', marker='o', linewidth=2)\n",
        "plt.fill_between(future_dates, sarima_conf.iloc[:, 0], sarima_conf.iloc[:, 1], color='blue', alpha=0.15, label='95% Confidence Interval')\n",
        "plt.title('3-Month Future Sales Forecast (SARIMA)', fontsize=14, fontweight='bold')\n",
        "plt.xlabel('Date')\n",
        "plt.ylabel('Sales ($)')\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# Cell 22: Markdown Task 3 Recommendation
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### Model Selection and Production Recommendation\n",
        "\n",
        "Based on the testing performance on the hold-out test set (Oct - Dec 2018):\n",
        "- **SARIMA** achieves the lowest **MAE (19,299.92)**, **RMSE (20,205.76)**, and **MAPE (20.36%)**.\n",
        "- **Prophet** follows closely with **MAE (20,296.01)** and **MAPE (21.89%)**.\n",
        "- **XGBoost** has the highest error rates: **MAE (24,286.79)** and **MAPE (25.41%)**.\n",
        "\n",
        "**Recommendation**: We recommend **SARIMA** for production use. It handles the linear trends and strong seasonality patterns in this dataset more accurately. XGBoost suffers in monthly settings due to the limited sample size (48 months total), which restricts its training capability, whereas SARIMA's statistical structure is highly robust on shorter, seasonal series."
    ]
})

# Cell 23: Markdown Task 4
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Task 4 — Product Category & Region Level Forecasting\n",
        "We repeat the SARIMA model separately to generate 3-month future forecasts for individual product categories and regions."
    ]
})

# Cell 24: Task 4 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "def forecast_segment(segment_df, steps=3):\n",
        "    segment_ts = segment_df.resample('MS', on='Order Date')['Sales'].sum()\n",
        "    all_months = pd.date_range(start='2015-01-01', end='2018-12-01', freq='MS')\n",
        "    segment_ts = segment_ts.reindex(all_months, fill_value=0)\n",
        "    \n",
        "    model = SARIMAX(segment_ts, order=best_order, seasonal_order=best_seasonal,\n",
        "                     enforce_stationarity=False, enforce_invertibility=False)\n",
        "    res = model.fit(disp=False)\n",
        "    forecast = res.forecast(steps=steps).values\n",
        "    return segment_ts, forecast\n",
        "\n",
        "segments = {\n",
        "    'Furniture': df[df['Category'] == 'Furniture'],\n",
        "    'Technology': df[df['Category'] == 'Technology'],\n",
        "    'Office Supplies': df[df['Category'] == 'Office Supplies'],\n",
        "    'West Region': df[df['Region'] == 'West'],\n",
        "    'East Region': df[df['Region'] == 'East']\n",
        "}\n",
        "\n",
        "plt.figure(figsize=(12, 7))\n",
        "future_dates = pd.date_range(start='2019-01-01', periods=3, freq='MS')\n",
        "segment_forecasts = {}\n",
        "\n",
        "for name, seg_df in segments.items():\n",
        "    hist, fore = forecast_segment(seg_df)\n",
        "    segment_forecasts[name] = fore\n",
        "    plt.plot(future_dates, fore, marker='o', label=f'{name} Forecast', linewidth=2)\n",
        "\n",
        "plt.title('Segment Sales Forecasts (Jan - Mar 2019) using SARIMA', fontsize=14, fontweight='bold')\n",
        "plt.xlabel('Date')\n",
        "plt.ylabel('Sales ($)')\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Print growth rates\n",
        "print('Segment projected growth (from Dec 2018 to Mar 2019):')\n",
        "for name, seg_df in segments.items():\n",
        "    hist_dec18 = seg_df.resample('MS', on='Order Date')['Sales'].sum().iloc[-1]\n",
        "    growth = ((segment_forecasts[name][-1] - hist_dec18) / hist_dec18) * 100\n",
        "    print(f'- {name}: {growth:+.2f}%')"
    ]
})

# Cell 25: Markdown Task 5
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Task 5 — Anomaly Detection in Sales Data\n",
        "We identify anomalous sales weeks using two methods:\n",
        "1. **Isolation Forest** (an unsupervised tree-based outlier algorithm)\n",
        "2. **Rolling Z-Score** (flagging dates where sales deviate by >2 standard deviations from the rolling mean)"
    ]
})

# Cell 26: Task 5 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "ts_weekly = df.resample('W', on='Order Date')['Sales'].sum()\n",
        "\n",
        "# 1. Isolation Forest\n",
        "iso_forest = IsolationForest(contamination=0.05, random_state=42)\n",
        "sales_features = ts_weekly.values.reshape(-1, 1)\n",
        "iso_anomalies = iso_forest.fit_predict(sales_features)\n",
        "anomaly_indices_if = np.where(iso_anomalies == -1)[0]\n",
        "\n",
        "# 2. Rolling Z-Score (8-week rolling window)\n",
        "rolling_mean = ts_weekly.rolling(window=8, min_periods=1).mean()\n",
        "rolling_std = ts_weekly.rolling(window=8, min_periods=1).std()\n",
        "rolling_std.iloc[0] = rolling_std.iloc[1] if len(rolling_std) > 1 else 1.0\n",
        "z_scores = (ts_weekly - rolling_mean) / rolling_std\n",
        "anomaly_indices_z = np.where(np.abs(z_scores) > 2)[0]\n",
        "\n",
        "# Plot anomalies\n",
        "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), sharex=True)\n",
        "\n",
        "ax1.plot(ts_weekly.index, ts_weekly.values, color='#1f77b4', label='Weekly Sales', alpha=0.7)\n",
        "ax1.scatter(ts_weekly.index[anomaly_indices_if], ts_weekly.values[anomaly_indices_if],\n",
        "            color='red', label='IF Outlier', marker='x', s=60, zorder=5)\n",
        "ax1.set_title('Isolation Forest Anomalies', fontsize=12, fontweight='bold')\n",
        "ax1.set_ylabel('Sales ($)')\n",
        "ax1.legend()\n",
        "\n",
        "ax2.plot(ts_weekly.index, ts_weekly.values, color='#1f77b4', label='Weekly Sales', alpha=0.7)\n",
        "ax2.scatter(ts_weekly.index[anomaly_indices_z], ts_weekly.values[anomaly_indices_z],\n",
        "            color='purple', label='Z-Score Outlier', marker='o', s=40, zorder=5)\n",
        "ax2.set_title('Z-Score Anomalies (>2 Std Dev from Rolling Mean)', fontsize=12, fontweight='bold')\n",
        "ax2.set_ylabel('Sales ($)')\n",
        "ax2.set_xlabel('Date')\n",
        "ax2.legend()\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Compare methods\n",
        "if_dates = set(ts_weekly.index[anomaly_indices_if])\n",
        "z_dates = set(ts_weekly.index[anomaly_indices_z])\n",
        "overlap_dates = if_dates.intersection(z_dates)\n",
        "\n",
        "print(f'Isolation Forest flagged {len(if_dates)} anomalies.')\n",
        "print(f'Z-Score flagged {len(z_dates)} anomalies.')\n",
        "print(f'Overlapping anomalies: {len(overlap_dates)}')\n",
        "print('Overlap Dates:', sorted(list(overlap_dates)))"
    ]
})

# Cell 27: Markdown Task 5 Discussion
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### Interpretation & Comparison of Anomaly Methods:\n",
        "- **Isolation Forest** isolates points that are globally different from the rest of the dataset. Therefore, it flags the absolute highest and lowest weeks as anomalies, regardless of when they occur.\n",
        "- **Rolling Z-Score** flags local fluctuations. It detects weeks where sales are significantly higher or lower than the surrounding 2 months. This is very good for identifying sudden, unexpected mid-season shifts.\n",
        "- The small overlap shows that they capture different aspects of data behavior: global outliers versus local trend deviations."
    ]
})

# Cell 28: Markdown Task 6
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Task 6 — Product Demand Segmentation using Clustering\n",
        "We group sub-categories into demand groups based on: Total Volume, YoY Growth rate, Sales Volatility, and Average Order Value."
    ]
})

# Cell 29: Task 6 Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Aggregate sub-category metrics\n",
        "sub_yearly = df.groupby(['Sub-Category', 'Year'])['Sales'].sum().unstack(level=1).fillna(0)\n",
        "sub_growth_rate = ((sub_yearly[2018] - sub_yearly[2017]) / sub_yearly[2017]) * 100\n",
        "sub_volume = df.groupby('Sub-Category')['Sales'].sum()\n",
        "sub_monthly_sales = df.groupby(['Sub-Category', pd.Grouper(key='Order Date', freq='MS')])['Sales'].sum().unstack(level=0).fillna(0)\n",
        "sub_volatility = sub_monthly_sales.std()\n",
        "sub_avg_order = df.groupby('Sub-Category').apply(lambda x: x['Sales'].sum() / x['Order ID'].nunique())\n",
        "\n",
        "clustering_df = pd.DataFrame({\n",
        "    'Total Volume': sub_volume,\n",
        "    'YoY Growth': sub_growth_rate,\n",
        "    'Sales Volatility': sub_volatility,\n",
        "    'Avg Order Value': sub_avg_order\n",
        "}).fillna(0)\n",
        "\n",
        "# Scale features\n",
        "scaler = StandardScaler()\n",
        "scaled_features = scaler.fit_transform(clustering_df)\n",
        "\n",
        "# Elbow Method\n",
        "inertia = []\n",
        "for k in range(1, 10):\n",
        "    kmeans = KMeans(n_clusters=k, random_state=42)\n",
        "    kmeans.fit(scaled_features)\n",
        "    inertia.append(kmeans.inertia_)\n",
        "\n",
        "plt.figure(figsize=(10, 5))\n",
        "plt.plot(range(1, 10), inertia, marker='o', color='#2ca02c')\n",
        "plt.title('Elbow Method for Product Demand Clustering', fontsize=14, fontweight='bold')\n",
        "plt.xlabel('Number of Clusters (K)')\n",
        "plt.ylabel('Inertia')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# K-Means on optimal K=4 clusters\n",
        "kmeans = KMeans(n_clusters=4, random_state=42)\n",
        "clustering_df['Cluster'] = kmeans.fit_predict(scaled_features)\n",
        "\n",
        "# PCA for 2D visualization\n",
        "pca = PCA(n_components=2, random_state=42)\n",
        "pca_features = pca.fit_transform(scaled_features)\n",
        "clustering_df['PCA1'] = pca_features[:, 0]\n",
        "clustering_df['PCA2'] = pca_features[:, 1]\n",
        "\n",
        "# Unique Labeling\n",
        "final_labels = {\n",
        "    0: 'Low Volume, High Volatility',\n",
        "    1: 'Declining Demand',\n",
        "    2: 'Growing Demand',\n",
        "    3: 'High Volume, Stable Demand'\n",
        "}\n",
        "clustering_df['Cluster Label'] = clustering_df['Cluster'].map(final_labels)\n",
        "\n",
        "# Plot clusters\n",
        "plt.figure(figsize=(12, 8))\n",
        "colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']\n",
        "for cid in range(4):\n",
        "    c_data = clustering_df[clustering_df['Cluster'] == cid]\n",
        "    plt.scatter(c_data['PCA1'], c_data['PCA2'], s=150, color=colors[cid], label=final_labels[cid], alpha=0.8, edgecolors='black')\n",
        "    for subcat, row in c_data.iterrows():\n",
        "        plt.annotate(subcat, (row['PCA1'], row['PCA2']), textcoords=\"offset points\", xytext=(0,10), ha='center', fontsize=9, fontweight='bold')\n",
        "\n",
        "plt.title('Product Demand Segmentation (K-Means on PCA)', fontsize=14, fontweight='bold')\n",
        "plt.xlabel('PCA 1')\n",
        "plt.ylabel('PCA 2')\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# Cell 30: Markdown Clustering Summary and stocking strategy
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### Cluster Labels and Stocking Recommendations:\n",
        "\n",
        "1. **High Volume, Stable Demand** (Binders, Chairs, Phones, Storage, Tables):\n",
        "   - *Stocking Strategy*: Implement standard replenishment intervals and optimize warehouse space to support continuous flow. Negotiate bulk pricing contracts with suppliers.\n",
        "2. **Low Volume, High Volatility** (Copiers, Machines):\n",
        "   - *Stocking Strategy*: Adopt a Just-In-Time (JIT) stocking policy or hold narrow safety stocks to prevent large cash hold-ups, as orders are sparse but expensive.\n",
        "3. **Growing Demand** (Accessories, Appliances, Art, Labels, Paper):\n",
        "   - *Stocking Strategy*: Keep safety stock high and plan buffer inventories ahead of seasonal spikes, allowing the supply chain to adapt to increasing sales trends.\n",
        "4. **Declining Demand** (Bookcases, Envelopes, Fasteners, Furnishings, Supplies):\n",
        "   - *Stocking Strategy*: Offer discount clearances to liquidate excess stocks, avoid ordering bulk volumes, and phase out underperforming product variants."
    ]
})

# Construct notebook dict
notebook = {
    "cells": cells,
    "metadata": {
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

# Write notebook file
with open('analysis.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Notebook analysis.ipynb written successfully! Executing it...")

# Execute the notebook programmatically so outputs are saved
with open('analysis.ipynb') as f:
    nb = nbformat.read(f, as_version=4)

ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
ep.preprocess(nb, {'metadata': {'path': './'}})

with open('analysis.ipynb', 'w') as f:
    nbformat.write(nb, f)

print("Notebook analysis.ipynb executed and updated successfully with outputs!")
